export const INIT_CONNECTION = 'initializeConnection'
export const INIT_CONTRACT = 'initializeContract'
export const AUTHENTICATE = 'authenticateUser'
export const POLL_WEB3 = 'pollWeb3'
export const LOGOUT = 'logOut'
export const UPDATE_BOUNTIES = 'updateBounties'
export const UPDATE_POLLS = 'updatePolls'
